### ISSUE TITLE
Emulate few spec breaking changes as acceptance criteria for the new Parser API

### ISSUE THREAD

**Issue by smoya** [asyncapi/shape-up-process#93]
Emulating new spec major versions that introduce breaking changes  will help us for:

- Validate the early design concepts at https://github.com/asyncapi/shape-up-process/issues/90.
- As acceptance criteria for tests at https://github.com/asyncapi/shape-up-process/issues/91

By emulating I mean just creating few spec documents where concepts are changed, such as split Operations, renaming fields, changing the deep level of some objects, reorder them, etc.

The outcome of this issue is a collection of either yaml or JsonSchema documents that introduce breaking changes.
They can be written here as a reference by now.

**Comment by smoya** [comment]
Based on https://github.com/asyncapi/shape-up-process/issues/73, and modifying a bit the StreetLights tutorial example, I emulated a possible breaking change on channels:

Current version:

```yaml
asyncapi: '2.0.0'
info:
  title: Streetlights API
  version: '1.0.0'
  description: |
    The Smartylighting Streetlights API allows you
    to remotely manage the city lights.
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
servers:
  mosquitto:
    url: mqtt://test.mosquitto.org
    protocol: mqtt
channels:
  light/measured:
    publish:
      summary: Inform about environmental lighting conditions for a particular streetlight.
      operationId: onLightMeasured
      message:
        payload:
          type: object
          properties:
            id:
              type: integer
              minimum: 0
              description: Id of the streetlight.
            lumens:
              type: integer
              minimum: 0
              description: Light intensity measured in lumens.
            sentAt:
              type: string
              format: date-time
              description: Date and time when the message was sent.
  light/measured/changed:
    subscribe:
      summary: Receive an update every time a lighting condition changed.
      operationId: onLightMeasureChanged
      message:
        payload:
          type: object
          properties:
            id:
              type: integer
              minimum: 0
              description: Id of the streetlight.
            lumens:
              type: integer
              minimum: 0
              description: Light intensity measured in lumens.
            sentAt:
              type: string
              format: date-time
              description: Date and time when the message was sent.
```

New version:

```yaml
asyncapi: '3.0.0-fake'
info:
  title: Streetlights API
  version: '1.0.0'
  description: |
    The Smartylighting Streetlights API allows you
    to remotely manage the city lights.
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
servers:
  mosquitto:
    url: mqtt://test.mosquitto.org
    protocol: mqtt
channels:
  light/measured:
    summary: Environmental lighting conditions for a particular streetlight
    operations: 
      - onLightMeasured
      - onLightMeasureChanged
components:
  operations:
    onLightMeasured:
      $ref: "#/components/messages/lightMeasured"
      summary: Inform about environmental lighting conditions for a particular streetlight.
    onLightMeasureChanged:
      $ref: "#/components/messages/lightMeasured"
      summary: Receive an update every time a lighting condition changed.
   messages:
    lightMeasured:
      message:
        payload:
          type: object
          properties:
            id:
              type: integer
              minimum: 0
              description: Id of the streetlight.
            lumens:
              type: integer
              minimum: 0
              description: Light intensity measured in lumens.
            sentAt:
              type: string
              format: date-time
              description: Date and time when the message was sent.
```

**Comment by smoya** [comment]
/progress 25 Emulated breaking change based on https://github.com/asyncapi/shape-up-process/issues/73

**Comment by smoya** [comment]
Another emualted version based on https://github.com/asyncapi/spec/issues/434 supporting multiple message `schemaFormat` values.

```yaml
asyncapi: '3.0.0-fake2'
# ...
channels:
  light/measured:
    publish:
      summary: Inform about environmental lighting conditions for a particular streetlight.
      operationId: onLightMeasured
      message:
        schemaFormat: 
         oneOf:
            - "application/vnd.apache.avro+json;version=1.9.0"
            - "application/vnd.oai.openapi;version=3.0.0"
        payload:
          type: object
          properties:
            id:
              type: integer
              minimum: 0
              description: Id of the streetlight.
            lumens:
              type: integer
              minimum: 0
              description: Light intensity measured in lumens.
            sentAt:
              type: string
              format: date-time
              description: Date and time when the message was sent.
 ```

**Comment by smoya** [comment]
/progress 65 Emulated breaking change based on https://github.com/asyncapi/spec/issues/434

**Comment by smoya** [comment]
Taking a couple of new approaches based on https://github.com/asyncapi/shape-up-process/issues/73:

### 1. Messages flow within a channel (still) through operations, but objects are decoupled.

```yaml
asyncapi: '3.0.0-fake3'
# ...
channels:
  light/measured:
    summary: Lighting conditions for a particular streetlight.
operations:
  onLightMeasured:
    operationType: publish
    summary: Inform about environmental lighting conditions for a particular streetlight.
    withMessage: lightMeasured
    withinChannel: light/measured
  onLightMeasureChanged:
    operationType: subscribe
    summary: Receive an update every time a lighting condition changed.
    withMessage: lightMeasured
    withinChannel: light/measured
messages:
  lightMeasured:
    payload:
      type: object
      properties:
        id:
          type: integer
          minimum: 0
          description: Id of the streetlight.
        lumens:
          type: integer
          minimum: 0
          description: Light intensity measured in lumens.
        sentAt:
          type: string
          format: date-time
          description: Date and time when the message was sent.
```

### 2. Messages are independent of channels. Messages within a channel can (optionally) be related to operations. Compatible with https://github.com/asyncapi/parser-js/issues/210

```yaml
asyncapi: '3.0.0-fake4'
# ...
channels:
  light/measured:
    summary: Lighting conditions for a particular streetlight.
    messages:
      - message: lightMeasured # this should exist in `messages`
        operations: 
          onLightMeasured:
            operationType: publish
            summary: Inform about environmental lighting conditions for a particular streetlight.
          onLightMeasureChanged:
            operationType: subscribe
            summary: Receive an update every time a lighting condition changed.
messages:
  lightMeasured:
    payload:
      type: object
      properties:
        id:
          type: integer
          minimum: 0
          description: Id of the streetlight.
        lumens:
          type: integer
          minimum: 0
          description: Light intensity measured in lumens.
        sentAt:
          type: string
          format: date-time
          description: Date and time when the message was sent.
```
